workflows:
  build:
    name: iOS Build & Test
    max_build_duration: 15
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
        - pull_request
        - tag
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
    scripts:
      - name: Test
        script: |
          #!/bin/sh
          set -ex
          xcode-project run-tests \
            --project "Stats.xcodeproj" \
            --scheme "Stats" \
            --test-xcargs "CODE_SIGNING_ALLOWED=NO"
        test_report: build/ios/test/*.xml
      - name: Build
        script: |
          xcodebuild build \
            -project "Stats.xcodeproj" \
            -scheme "Stats" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      - name: Extract .ipa (unsigned)
        script: |
          mkdir Payload
          cp -r $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Debug-iphoneos/*.app Payload
          zip -r build.ipa Payload
          rm -rf Payload
    artifacts:
      - build.ipa
