workflows:
  build:
    name: iOS Build & Test
    max_build_duration: 15
    instance_type: mac_mini_m1
    environment:
      groups:
        - GitHub
    triggering:
      events:
        - push
        - pull_request
        - tag
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
    scripts:
      - name: Build
        script: |
          xcodebuild build \
            -project "Stats.xcodeproj" \
            -scheme "Stats" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      - name: Extract .ipa (unsigned)
        script: |
          mkdir Payload
          cp -r $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Debug-iphoneos/*.app Payload
          zip -r build.ipa Payload
          rm -rf Payload
      - name: Publish to GitHub
        script: |
          #!/usr/bin/env zsh

          # Publish only for tag builds
          if [ -z ${CM_TAG} ]; then
            echo "Not a tag build, will not publish GitHub release"
            exit 0
          fi

          gh release create "${CM_TAG}" \
            --title "Stats ${CM_TAG}" \
            build.ipa
    artifacts:
      - build.ipa
